{{- $valueFiles := .Values.source.helm.valueFiles }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.source.repoUrl }}
    targetRevision: {{ .Values.source.targetRevision }}
    path: {{ .Values.source.path }}
    helm:
      values: {{ toYaml .Values.source.helm.values | toString | indent 6 }}
      {{- if gt (len $valueFiles) 0 }}
      valueFiles:
      - values.yaml
      {{- toYaml $valueFiles | nindent 6 }}
      {{- end }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.namespace }}
  syncPolicy:
    {{- if eq .Values.autoSyncPolicy "enabled"}}
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    {{- end }}
    retry:
      backoff:
        duration: "10s"
        factor: 2
        maxDuration: "3m"
    syncOptions:
      - "Validate=false" # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default )
      - "CreateNamespace=true" # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
      - "PrunePropagationPolicy=foreground" # Supported policies are background, foreground and orphan.
      - "PruneLast=true" # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
