apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: {{ .Values.name }}
spec:
  interval: 2m0s
  url: {{ .Values.url }}
  ref:
    branch: {{ .Values.branch }}
  secretRef:
    name: {{ .Values.secretRefName }}
